// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJOCwhc22JVVNHUXVDm4qtYk1my-He0g',
    appId: '1:493479067260:web:2f35e76884c61afa1d13f9',
    messagingSenderId: '493479067260',
    projectId: 'projetfinal-2b131',
    authDomain: 'projetfinal-2b131.firebaseapp.com',
    storageBucket: 'projetfinal-2b131.appspot.com',
    measurementId: 'G-ZH5GW7J9WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAJ0lj_FrUz-u_JYwwoVTUoeMIAXv9UVI',
    appId: '1:493479067260:android:df1ca2820ef5a3f91d13f9',
    messagingSenderId: '493479067260',
    projectId: 'projetfinal-2b131',
    storageBucket: 'projetfinal-2b131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvsV-Rd4kQ0Pa_QdwqaVUkvrz2Kn7JsNw',
    appId: '1:493479067260:ios:5f52f4cbde1640fe1d13f9',
    messagingSenderId: '493479067260',
    projectId: 'projetfinal-2b131',
    storageBucket: 'projetfinal-2b131.appspot.com',
    iosBundleId: 'com.example.finalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvsV-Rd4kQ0Pa_QdwqaVUkvrz2Kn7JsNw',
    appId: '1:493479067260:ios:fd2cbf8ad09cb23e1d13f9',
    messagingSenderId: '493479067260',
    projectId: 'projetfinal-2b131',
    storageBucket: 'projetfinal-2b131.appspot.com',
    iosBundleId: 'com.example.finalproject.RunnerTests',
  );
}
